// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}

type UserByGoodsRequest struct {
	Userid  int `form:"userid"`  //用户ID
	Goodsid int `form:"goodsid"` // 商品ID
	Count   int `form:"count"`   // 购买数量
	Pay     int `form:"pay"`     // 支付方式
}
