// Code generated by goctl. DO NOT EDIT.
// Source: goods_srv.proto

package server

import (
	"context"

	"2112a-6/month/wsyx/goods_srv/goods_srv"
	"2112a-6/month/wsyx/goods_srv/internal/logic"
	"2112a-6/month/wsyx/goods_srv/internal/svc"
)

type GoodsSrvServer struct {
	svcCtx *svc.ServiceContext
	goods_srv.UnimplementedGoodsSrvServer
}

func NewGoodsSrvServer(svcCtx *svc.ServiceContext) *GoodsSrvServer {
	return &GoodsSrvServer{
		svcCtx: svcCtx,
	}
}

func (s *GoodsSrvServer) Ping(ctx context.Context, in *goods_srv.Request) (*goods_srv.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
