// Code generated by goctl. DO NOT EDIT.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	scoreFieldNames          = builder.RawFieldNames(&Score{})
	scoreRows                = strings.Join(scoreFieldNames, ",")
	scoreRowsExpectAutoSet   = strings.Join(stringx.Remove(scoreFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	scoreRowsWithPlaceHolder = strings.Join(stringx.Remove(scoreFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	scoreModel interface {
		Insert(ctx context.Context, data *Score) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Score, error)
		Update(ctx context.Context, data *Score) error
		TranDelUpdate( tx *sql.Tx, score ,userid int) error
		TranInsUpdate(tx *sql.Tx, score ,userid int) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultScoreModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Score struct {
		Id     uint64 `db:"id"`
		UserId int64  `db:"user_id"`
		Score  uint64 `db:"score"`
	}
)

func newScoreModel(conn sqlx.SqlConn) *defaultScoreModel {
	return &defaultScoreModel{
		conn:  conn,
		table: "`score`",
	}
}

func (m *defaultScoreModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultScoreModel) FindOne(ctx context.Context, id uint64) (*Score, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", scoreRows, m.table)
	var resp Score
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultScoreModel) Insert(ctx context.Context, data *Score) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, scoreRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Score)
	return ret, err
}

func (m *defaultScoreModel) Update(ctx context.Context, data *Score) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, scoreRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Score, data.Id)
	return err
}
func (m *defaultScoreModel) TranDelUpdate(tx *sql.Tx, score ,userid int) error {
	//"update `score` set score=score+? where user_id=?
	query := fmt.Sprintf("update %s set score=score-?   where `user_id` = ?", m.table)
	_, err := tx.Exec( query,score,userid)

	return err
}
func (m *defaultScoreModel) TranInsUpdate(tx *sql.Tx, score ,userid int) error {
	query := fmt.Sprintf("update %s set score=score+?   where `user_id` = ?", m.table)
	_, err := tx.Exec( query,score,userid)
	return err
}
func (m *defaultScoreModel) tableName() string {
	return m.table
}
