// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: goods_srv.proto

package goods_srv

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GoodsSrv_Ping_FullMethodName = "/goods_srv.Goods_srv/Ping"
)

// GoodsSrvClient is the client API for GoodsSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoodsSrvClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type goodsSrvClient struct {
	cc grpc.ClientConnInterface
}

func NewGoodsSrvClient(cc grpc.ClientConnInterface) GoodsSrvClient {
	return &goodsSrvClient{cc}
}

func (c *goodsSrvClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, GoodsSrv_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoodsSrvServer is the server API for GoodsSrv service.
// All implementations must embed UnimplementedGoodsSrvServer
// for forward compatibility
type GoodsSrvServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedGoodsSrvServer()
}

// UnimplementedGoodsSrvServer must be embedded to have forward compatible implementations.
type UnimplementedGoodsSrvServer struct {
}

func (UnimplementedGoodsSrvServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedGoodsSrvServer) mustEmbedUnimplementedGoodsSrvServer() {}

// UnsafeGoodsSrvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoodsSrvServer will
// result in compilation errors.
type UnsafeGoodsSrvServer interface {
	mustEmbedUnimplementedGoodsSrvServer()
}

func RegisterGoodsSrvServer(s grpc.ServiceRegistrar, srv GoodsSrvServer) {
	s.RegisterService(&GoodsSrv_ServiceDesc, srv)
}

func _GoodsSrv_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsSrvServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoodsSrv_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsSrvServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// GoodsSrv_ServiceDesc is the grpc.ServiceDesc for GoodsSrv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoodsSrv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goods_srv.Goods_srv",
	HandlerType: (*GoodsSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _GoodsSrv_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goods_srv.proto",
}
