// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"2112a-6/month/wsyx/wsyx_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/Dtm/Usergoods",
				Handler: DtmAddUserbyGoodsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/add/Usergoods",
				Handler: AddUserbyGoodsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: Wsyx_apiHandler(serverCtx),
			},
		},
	)
}
