// Code generated by goctl. DO NOT EDIT.
// Source: score_srv.proto

package server

import (
	"context"

	"2112a-6/month/wsyx/score_srv/internal/logic"
	"2112a-6/month/wsyx/score_srv/internal/svc"
	"2112a-6/month/wsyx/score_srv/score_srv"
)

type ScoreSrvServer struct {
	svcCtx *svc.ServiceContext
	score_srv.UnimplementedScoreSrvServer
}

func NewScoreSrvServer(svcCtx *svc.ServiceContext) *ScoreSrvServer {
	return &ScoreSrvServer{
		svcCtx: svcCtx,
	}
}

func (s *ScoreSrvServer) Ping(ctx context.Context, in *score_srv.Request) (*score_srv.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *ScoreSrvServer) AddUserScore(ctx context.Context, in *score_srv.AddUserScoreRequest) (*score_srv.AddUserScoreResponse, error) {
	l := logic.NewAddUserScoreLogic(ctx, s.svcCtx)
	return l.AddUserScore(in)
}

func (s *ScoreSrvServer) TranInsScore(ctx context.Context, in *score_srv.AddUserScoreRequest) (*score_srv.AddUserScoreResponse, error) {
	l := logic.NewTranInsScoreLogic(ctx, s.svcCtx)
	return l.TranInsScore(in)
}

func (s *ScoreSrvServer) TranDelScore(ctx context.Context, in *score_srv.AddUserScoreRequest) (*score_srv.AddUserScoreResponse, error) {
	l := logic.NewTranDelScoreLogic(ctx, s.svcCtx)
	return l.TranDelScore(in)
}
