// Code generated by goctl. DO NOT EDIT.
// Source: goods_srv.proto

package goodssrvclient

import (
	"context"

	"2112a-6/month/wsyx/goods_srv/goods_srv"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = goods_srv.Request
	Response = goods_srv.Response

	GoodsSrv interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultGoodsSrv struct {
		cli zrpc.Client
	}
)

func NewGoodsSrv(cli zrpc.Client) GoodsSrv {
	return &defaultGoodsSrv{
		cli: cli,
	}
}

func (m *defaultGoodsSrv) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := goods_srv.NewGoodsSrvClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
